
// export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
// export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
// export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

// export const FETCH_FILTER_REQUEST = 'FETCH_FILTER_REQUEST';
// export const FETCH_FILTER_SUCCESS = 'FETCH_FILTER_SUCCESS';
// export const FETCH_FILTER_FAILURE = 'FETCH_FILTER_FAILURE';

// export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST';
// export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
// export const FETCH_SEARCH_FAILURE = 'FETCH_SEARCH_FAILURE';

// export const FETCH_SEARCH_DROPDOWN_REQUEST = 'FETCH_SEARCH_DROPDOWN_REQUEST';
// export const FETCH_SEARCH_DROPDOWN_SUCCESS = 'FETCH_SEARCH_DROPDOWN_SUCCESS';
// export const FETCH_SEARCH_DROPDOWN_FAILURE = 'FETCH_SEARCH_DROPDOWN_FAILURE';

// export const GET_SINGLE_PRODUCT_REQUEST = 'GET_SINGLE_PRODUCT_REQUEST';
// export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS';
// export const GET_SINGLE_PRODUCT_FAILURE = 'GET_SINGLE_PRODUCT_FAILURE';

// export const ADD_PRODUCT_CART_REQUEST = 'ADD_PRODUCT_CART_REQUEST';
// export const ADD_PRODUCT_CART_SUCCESS = 'ADD_PRODUCT_CART_SUCCESS';
// export const ADD_PRODUCT_CART_FAILURE = 'ADD_PRODUCT_CART_FAILURE';

// export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST';
// export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
// export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';

// export const REMOVE_PRODUCT_CART_REQUEST = 'REMOVE_PRODUCT_CART_REQUEST';
// export const REMOVE_PRODUCT_CART_SUCCESS = 'REMOVE_PRODUCT_CART_SUCCESS';
// export const REMOVE_PRODUCT_CART_FAILURE = 'REMOVE_PRODUCT_CART_FAILURE';

// export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST';
// export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
// export const ADD_ORDER_FAILURE = 'ADD_ORDER_FAILURE';

// export const EMPTY_CART_REQUEST = 'EMPTY_CART_REQUEST';
// export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS';
// export const EMPTY_CART_FAILURE = 'EMPTY_CART_FAILURE';

// export const FETCH_ORDER_REQUEST = 'FETCH_ORDER_REQUEST';
// export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
// export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';

// export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
// export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
// export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';

// export const EDIT_PRODUCT_REQUEST = 'EDIT_PRODUCT_REQUEST';
// export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
// export const EDIT_PRODUCT_FAILURE = 'EDIT_PRODUCT_FAILURE';

// export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
// export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
// export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE';

// export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
// export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
// export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE';

// export const START_LOADING = 'START_LOADING ';
// export const STOP_LOADING = 'STOP_LOADING ';
